# Generated by Django 2.0 on 2018-03-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coingysettings',
            name='position_type',
        ),
        migrations.AddField(
            model_name='coinpair',
            name='position_type',
            field=models.CharField(choices=[('history', 'История'), ('asks', 'asks'), ('bids', 'bids'), ('orders', 'orders'), ('all', 'all')], default='all', max_length=6),
            preserve_default=False,
        ),
    ]
