# Generated by Django 2.0 on 2018-03-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_bot', '0002_auto_20180307_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketposition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
