# Generated by Django 2.0 on 2018-03-12 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_bot', '0004_marketposition_wall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketposition',
            name='wall',
        ),
    ]
