# Generated by Django 2.0 on 2018-03-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_bot', '0005_remove_marketposition_wall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coingysettings',
            name='min_wall',
        ),
        migrations.AddField(
            model_name='coinpair',
            name='min_wall',
            field=models.FloatField(null=True),
        ),
    ]
