# Generated by Django 2.0 on 2018-03-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_bot', '0006_auto_20180312_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinpair',
            name='min_wall',
            field=models.FloatField(default=50),
        ),
    ]
