version: '2'

services:
  db:
    image: postgres:9.6
    hostname: db
    restart: on-failure
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mining
    volumes:
      - db:/var/lib/postgresql
    ports:
      - "5435:5432"

  redis:
    image: redis:3.0
    hostname: redis
    ports:
      - "6379"

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.6.0
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin


  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    restart: always
    command: ./run_django.bash
    environment:
      - DEBUG
    volumes:
      - .:/usr/src/app
      - static:/var/www/static
      - ./media:/var/www/media
    ports:
      - "8002:8000"
    links:
      - db
      - redis

    depends_on:
      - db
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DEBUG
    command: ./run_celery.bash
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - ./media:/var/www/media
    links:
      - db
      - redis
    depends_on:
      - db



  nginx:
    image: nginx:1.13
    volumes:
      - ./miningPlatform/nginx/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
      - web
    ports:
      - "80:80"
    links:
      - web


volumes:
  db:
  static:
  media:
